apiVersion: v1
kind: Pod
metadata:
  name: configmap-mount-pod
  labels:
    app: configmap-example
spec:
  containers:
    - name: app-container
      image: nginx:latest
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: example-configmap

---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: sync-wait-job
#   # annotations:
#   #   argocd.argoproj.io/hook: PreSync
# spec:
#   template:
#     spec:
#       containers:
#         - name: wait-container
#           image: busybox
#           command: ["sh", "-c", "sleep 300"]  # Introduce a delay of 25 seconds
#           volumeMounts:
#             - name: dummy-config
#               mountPath: /etc/dummy
#       volumes:
#         - name: dummy-config
#           configMap:
#             name: dummy-configmap
#       restartPolicy: Never
---
apiVersion: v1
data:
  foo: bar
  goo: car
  test: trial
  benda: beera
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm, Delete=confirm
  name: somecm
---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: sleep-app
#   labels:
#     app: sleep-app
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: sleep-app
#   template:
#     metadata:
#       labels:
#         app: sleep-app
#     spec:
#       containers:
#         - name: sleep-container
#           image: busybox
#           command: ["sh", "-c", "sleep 50"]  
---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: my-secret
# type: Opaque
# data:
#   username: +++++++dXNlcm5hbWU=  # Base64 encoded value of "username"
#   password: cGFzc3dvcmQ=  # Base64 encoded value of "password"
