apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd2-install
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.4.7
    chart: argo-cd
  destination:
    server: https://argocd2.argotest.opsmx.net:443
    #your cluster name'
    namespace: argocd
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
