# job-sleep.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: sleep-job
spec:
  template:
    spec:
      containers:
      - name: sleep-container
        image: busybox
        command: ["sleep", "300"] # Sleep for 5 minutes (300 seconds)
      restartPolicy: Never
  backoffLimit: 4
