name: Custom Runner CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted  # This will run on your custom runner
    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v4  # Fetches your code

      - name: Display system information
        run: |
          echo "Running on a self-hosted runner"
          uname -a
          whoami
          
      - name: Show changes in the latest commit
        run: |
          echo "Recent changes in the repository:"
          git fetch origin main --depth=2  # Fetch the latest two commits for comparison
          git diff HEAD^ HEAD  # Show the changes between the latest commit and the previous commit
          git diff --name-only HEAD^ HEAD  # file name have made changes
      - name: Run a sample script
        run: |
          echo "Hello from Custom Runner!"
          ls -l
