name: PR File Change Checker test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  detect-file-changes:
    name: Detect Changed Files
    runs-on: cluster2  # Use your runner label here

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3

      - name: Get list of changed files
        id: changed-files
        run: |
          echo "Fetching changed files in PR #${{ github.event.pull_request.number }}"
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt

      - name: Upload changed files list as artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: changed-files
          path: changed_files.txt
