name: PR File Change Checker

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  detect-file-changes:
    name: Get Changed Files in PR
    runs-on: cluster2

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Required for diff

      - name: Show changed files
        run: |
          echo "Base ref: ${{ github.event.pull_request.base.ref }}"
          echo "Head ref: ${{ github.event.pull_request.head.ref }}"

          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD > changed_files.txt

          echo "Changed files:"
          cat changed_files.txt
