name: PR File Change Checker

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  detect-file-changes:
    name: Get Changed Files in PR
    runs-on: cluster2  # Use your custom runner label

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch base branch and compare changes
        run: |
          echo "Base ref: ${{ github.event.pull_request.base.ref }}"
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt

      - name: Upload changed files list as artifact
        uses: actions/upload-artifact@v2
        with:
          name: changed-files
          path: changed_files.txt
